# Generated by Django 5.0.2 on 2024-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(default='defaultFirstName', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='defaultLastName', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(default='1234567890', max_length=20),
            preserve_default=False,
        ),
    ]
