# Generated by Django 5.0.2 on 2024-03-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_ticket_email_ticket_first_name_ticket_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
